# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  
   
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy image

  jobs:
  - job: print name
    displayName: Print job name
    pool: Default
    
    steps:
    - task: cURLUploader@2
      inputs:
       url: 'https://snsina.github.io/'
