# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  
   
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
  - job: 'print_default_working_directory'
    displayName: print_dir_path
    pool: Default

    steps:
    - script: pwd $(System.DefaultWorkingDirectory)

- stage: Deploy_sandbox
  displayName: Deploy image
  variables:
    - group: sandbox

  jobs:
  - deployment: Deploy_sandbox    
    displayName: Print job name
    environment: 'sandbox'
    pool: Default
    
    strategy:
     runOnce:
       deploy:
        steps:
        - task: CmdLine@2
          displayName: curl
          inputs:
            script: 'curl $(url)'

- stage: Deploy_prod
  displayName: Deploy image
  variables:
    - group: prod

  jobs:
  - deployment: Deploy    
    displayName: Print job name
    environment: 'prod'
    pool: Default
    
    strategy:
     runOnce:
       deploy:
        steps:
        - task: CmdLine@2
          displayName: curl
          inputs:
            script: 'curl $(url)'