name: snsinahub-valet/Cirecle-migration/running-steps
on:
  push:
    branches:
    - main
jobs:
  step-1:
    runs-on: ubuntu-latest
    container:
      image: docker:17.05.0-ce-git
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      id: qemu
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: install dependencies
      run: "apk add --no-cache \\\n  py-pip=9.0.0-r1\npip install --upgrade pip \\\npip install \\\n  docker-compose==1.12.0 \\\n  awscli==1.11.76 \n"
    - name: build docker image
      run: "docker build -t snsinahub-valet/circleci-migration:1.0.0 .            \n"
  step-2:
    runs-on: ubuntu-latest
    container:
      image: python:3.6
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      id: qemu
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: Docker build
      run: |-
        docker build \
        -t docker.io/snsinahub-valet/aws-migration:$GITHUB_SHA
      timeout-minutes: 10
